# configuration document for shopee_scraper

# HTTP
headers:
  user_agent: Mozilla/5.0
max_requests: 2000000

# Proxies
proxy_urls: []
proxy_user: placeholder
proxy_pass: placeholder
proxy_port: placeholder

# Redis
redis_host: localhost
redis_port: 6379
redis_db: 0
