# configuration document for shopee_scraper

# crawler
category_level: main
max_threads: 200

# HTTP
headers:
  user-agent: Mozilla/5.0
max_requests: 2000000

# MySQL
host: scrapingdb.cexqjqkwvxs5.us-east-1.rds.amazonaws.com
user: nad385
pw: 9dETROIT^
db_name: shopee

# Proxies
proxy_user: lum-customer-hl_4300955c-zone-static
proxy_pass: qrab6knjacsq
proxy_port: 22225

# Redis
redis_host: localhost
redis_port: 6379
redis_db: 0
